# Introduction to Pytorch

## 1. Tensors
A tensor is a multidimensional matrix containing elements of a single data type

In [2]:
import torch
# creating a scaler -> torch.empty(size)
x = torch.empty(1)
print(x)

tensor([3.5891e+32])


In [3]:
# creating a vector
vec = torch.empty(3)
print(vec)

tensor([6.5635e+17, 4.3963e-41, 2.3997e-14])


In [4]:
# creating a 2 x 3 matrix -> row x column
x1 = torch.empty(2,3)
print(x1)

tensor([[ 3.2458e-11,  0.0000e+00,  3.2530e-11],
        [ 0.0000e+00, -4.9628e-05,  1.1262e+10]])


In [5]:
# creating a tensor - 3 dimensions
x2 = torch.empty(2,2,3)
print("3 dimension tensor",x2)
# create a 4 dimension tensor
x3 = torch.empty(2,2,2,3)
print("4 dimension tensor", x3)

3 dimension tensor tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
4 dimension tensor tensor([[[[3.2458e-11, 0.0000e+00, 3.2597e-11],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 1.5835e-43],
          [0.0000e+00, 3.2450e-11, 0.0000e+00]],

         [[6.5635e+17, 4.3963e-41, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [6]:
# random numbers btw 0 and 1
x4 = torch.rand(5,3)
print("Random numbers btw 0 and 1", x4)

Random numbers btw 0 and 1 tensor([[0.3792, 0.2285, 0.5642],
        [0.9743, 0.6460, 0.7026],
        [0.5246, 0.2118, 0.0139],
        [0.3156, 0.5823, 0.6631],
        [0.9192, 0.0786, 0.2121]])


In [7]:
# fill with zeros -> torch.zeros(size)
x5 = torch.zeros(3)
print(x5)
x_5= torch.zeros(3,5)
print(x_5)

tensor([0., 0., 0.])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
# fill with ones
x6 = torch.ones(6)
print(x6)
x_6 = torch.ones(3,4)
print(x_6)

tensor([1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
# check size of a tensor
y = torch.empty(2,3,3,4)
print(y)
print("Size of tensor y:", y.size()) # y.shape
# access a given dimension
print(y.size(2))

tensor([[[[6.5637e+17, 4.3963e-41, 6.5637e+17, 4.3963e-41],
          [4.4842e-44, 0.0000e+00, 8.9683e-44, 0.0000e+00],
          [3.2224e-11, 0.0000e+00, 0.0000e+00, 2.3510e-38]],

         [[1.6308e-14, 0.0000e+00, 1.0842e-19, 0.0000e+00],
          [1.7256e-11, 0.0000e+00, 3.2600e-11, 0.0000e+00],
          [1.3563e-19, 1.9515e-19, 4.6243e-44, 0.0000e+00]],

         [[3.2604e-11, 0.0000e+00, 1.7267e-11, 0.0000e+00],
          [1.7937e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
          [1.6970e-11, 0.0000e+00, 1.0000e+00, 1.0000e+00]]],


        [[[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
          [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
          [2.6905e-43, 0.0000e+00, 1.1210e-43, 0.0000e+00]],

         [[3.2225e-11, 0.0000e+00, 1.3563e-19, 1.3563e-19],
          [1.3563e-19, 1.3563e-19, 5.0746e+31, 8.9784e-33],
          [1.3563e-19, 1.3563e-19, 2.7045e-43, 0.0000e+00]],

         [[1.7239e-11, 0.0000e+00, 6.5634e+17, 4.3963e-41],
          [5.2097e-11, 4.437

In [10]:
# check data type
print("data type of tensor y", y.dtype)

# specify data type
x = torch.zeros(5,3, dtype=torch.float16)
print(x, x.dtype)

data type of tensor y torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16) torch.float16


In [11]:
# construct from data
x = torch.tensor([5.5, 3.4, 43.43])
print(x, x.dtype)

tensor([ 5.5000,  3.4000, 43.4300]) torch.float32


In [14]:
# requires_grad argument -> tells pytorch that it needs to calculate gradient for this tensor
t = torch.tensor([5.5, 3,4],requires_grad=True)
print(t, t.dtype)

tensor([5.5000, 3.0000, 4.0000], requires_grad=True) torch.float32


## Tensor Operations

In [21]:
x = torch.ones(2,2)
y = torch.rand(2,2)

# addition
sum = x + y
print("sum",sum)
print(torch.add(x,y)) # a cleaner way

# subtraction
print("subtraction", torch.sub(x,y))

# multiplication
print("multiplication", torch.mul(x,y))

# division
print("division", torch.div(x,y))

# inplace addition
print("inplace addition",y.add_(x))



sum tensor([[1.4366, 1.5979],
        [1.1885, 1.4957]])
tensor([[1.4366, 1.5979],
        [1.1885, 1.4957]])
subtraction tensor([[0.5634, 0.4021],
        [0.8115, 0.5043]])
multiplication tensor([[0.4366, 0.5979],
        [0.1885, 0.4957]])
division tensor([[2.2905, 1.6726],
        [5.3042, 2.0174]])
inplace addition tensor([[1.4366, 1.5979],
        [1.1885, 1.4957]])


In [30]:
# slicing
r = torch.rand(5,4)
print(r)

# all rows, 0 column 0
print(r[:, 0])

# print row 1, all columns
print(r[1,:])

# element 1,3
print(r[1,3])

# get the actual value if only 1 element in your tensor
print(r[1,2].item())

print(r.shape)

tensor([[0.6839, 0.5835, 0.4038, 0.1735],
        [0.3103, 0.9227, 0.8516, 0.1881],
        [0.4182, 0.9652, 0.2936, 0.8021],
        [0.2600, 0.1851, 0.5368, 0.7479],
        [0.2592, 0.5945, 0.5283, 0.8994]])
tensor([0.6839, 0.3103, 0.4182, 0.2600, 0.2592])
tensor([0.3103, 0.9227, 0.8516, 0.1881])
tensor(0.1881)
0.8516247868537903
torch.Size([5, 4])


In [36]:
# reshape the tensor
print(r)
s = r.view(20)
print("s: ",s, s.shape)

s_new = r.view(-1, 5)
print("s_new", s_new)



tensor([[0.6839, 0.5835, 0.4038, 0.1735],
        [0.3103, 0.9227, 0.8516, 0.1881],
        [0.4182, 0.9652, 0.2936, 0.8021],
        [0.2600, 0.1851, 0.5368, 0.7479],
        [0.2592, 0.5945, 0.5283, 0.8994]])
s:  tensor([0.6839, 0.5835, 0.4038, 0.1735, 0.3103, 0.9227, 0.8516, 0.1881, 0.4182,
        0.9652, 0.2936, 0.8021, 0.2600, 0.1851, 0.5368, 0.7479, 0.2592, 0.5945,
        0.5283, 0.8994]) torch.Size([20])
s_new tensor([[0.6839, 0.5835, 0.4038, 0.1735, 0.3103],
        [0.9227, 0.8516, 0.1881, 0.4182, 0.9652],
        [0.2936, 0.8021, 0.2600, 0.1851, 0.5368],
        [0.7479, 0.2592, 0.5945, 0.5283, 0.8994]])


In [37]:
# convert tensor to numpy array and vice versa
print("r tensor:", r)
ss = r.numpy()
print("ss numpy array:", ss, type(ss))


r tensor: tensor([[0.6839, 0.5835, 0.4038, 0.1735],
        [0.3103, 0.9227, 0.8516, 0.1881],
        [0.4182, 0.9652, 0.2936, 0.8021],
        [0.2600, 0.1851, 0.5368, 0.7479],
        [0.2592, 0.5945, 0.5283, 0.8994]])
ss numpy array: [[0.68394715 0.5835182  0.4037674  0.17345715]
 [0.31026703 0.9227203  0.8516248  0.188137  ]
 [0.4182368  0.965195   0.2936105  0.80205446]
 [0.25998676 0.18510675 0.5368074  0.7479188 ]
 [0.25915444 0.59451383 0.52825636 0.89938223]] <class 'numpy.ndarray'>


In [41]:
# numpy array to tensor
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# same as
c = torch.tensor(a)
print(c)

# in cpu, tensor and numpy array will share the same memory address
a += 1
print("This is a:", a)
print("This is b:", b) # it got modified because they share the same memory address in CPU


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
This is a: [2. 2. 2. 2. 2.]
This is b: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## GPU Support


In [43]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

x = torch.rand(2,2).to(device) # move tensor to available GPU
# x = x.to("cpu")

y = torch.rand(3,3, device= device) # create directly in GPU


cpu


### AutoGrad
Autograd package provide automatic differentiation for operations on Tensors.
- torch.autograd is an engine for computing the vector-Jacobian product. It computes partial derivatives while applying the chain rule

In [59]:
t = torch.rand(3, requires_grad=True)
u = t + 2
print(t)
print(u) # u was created as a result of an operation, it has grad_fn attribute
# grad_fn -> references a function that has created the tensor

z = u * u * 3
print("z: ",z)
z = z.mean()
print("mean of z: ", z.mean())
print(u.grad)
z.backward() # calculate the gradient with backpropagation
print(u.grad)
# print("gradient of x: ", t.grad)

tensor([0.3258, 0.7501, 0.3601], requires_grad=True)
tensor([2.3258, 2.7501, 2.3601], grad_fn=<AddBackward0>)
z:  tensor([16.2285, 22.6887, 16.7107], grad_fn=<MulBackward0>)
mean of z:  tensor(18.5426, grad_fn=<MeanBackward0>)
None
None


/tmp/ipython-input-1230800906.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(u.grad)
/tmp/ipython-input-1230800906.py:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull

 ## Stop a tensor from tracking history
- Ex. during the training loop when we want to update weights or after training during evaluation
- to prevent that we can use;
- x.requires_grad(False)
- x.detach()
- wrap in wtih torch.no_grad()

In [65]:
a = torch.randn(3,3) # randn -> standard normal dist. mean = 0, standard deviation = 1, range -infinity to +infinity : value cluster around 0
# rand() => uniform distribution, range[0,1]
b = (a * a).sum()
print(a, a.dtype)
print(a.requires_grad)
print(b.grad_fn)

a.requires_grad_(True)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)


tensor([[-0.5218,  0.1600,  0.3171],
        [-0.0986,  1.0983, -0.2332],
        [-0.1094, -1.4842, -2.2896]]) torch.float32
False
None
True


In [66]:
#.detach()
a = torch.randn(3,3, requires_grad=True)
b = a.detach()
print(a.requires_grad)
print(b.requires_grad)


True
False


In [68]:
# wrap in with 'torch.no_grad()'
a = torch.randn(2,2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
  b = a**2
  print(b.requires_grad)

True
False


## Gradient Descent Autograd
Linear regression: f(x) = w*x +b
- where w = weights, b = bias


In [69]:
import torch
# f = w * x +b
x = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.float32)
y = torch.tensor([2,4,6,8,10,12,14,16], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
  return w * x

# loss = MSE
def loss(y, y_pred):
  return ((y_pred - y)**2).mean()

x_test = 5.0

print(f'Prediction before training: f({x_test}) = {forward(x_test).item():.3f}')


Prediction before training: f(5.0) = 0.000


In [75]:
# Training
learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs):
  # predict = forward pass
  y_pred = forward(x)
  # loss
  l = loss(y, y_pred)
  # calculate gradients = backward pass
  l.backward()

  # update weights
  # w.data = w.data - learning)rate * w.grad
  with torch.no_grad():
    w -= learning_rate * w.grad # gradient descent
  # zero the gradients after updating
  w.grad.zero_()

  if (epoch+1) % 10 == 0:
    print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.3f}')

print(f'Prediction after training: f({x_test}) = {forward(x_test).item():.3f}')

epoch 10: w = 2.000, loss = 0.000
epoch 20: w = 2.000, loss = 0.000
epoch 30: w = 2.000, loss = 0.000
epoch 40: w = 2.000, loss = 0.000
epoch 50: w = 2.000, loss = 0.000
epoch 60: w = 2.000, loss = 0.000
epoch 70: w = 2.000, loss = 0.000
epoch 80: w = 2.000, loss = 0.000
epoch 90: w = 2.000, loss = 0.000
epoch 100: w = 2.000, loss = 0.000
Prediction after training: f(5.0) = 10.000
